// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW4wBm9vyN2znAfDqu4_ysit-rfmBRIDg',
    appId: '1:588664787435:web:a70d53fe110bf5db3ac9ae',
    messagingSenderId: '588664787435',
    projectId: 'mynotes-101-331ef',
    authDomain: 'mynotes-101-331ef.firebaseapp.com',
    storageBucket: 'mynotes-101-331ef.appspot.com',
    measurementId: 'G-HXNKZS4KD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9KZwAJXFfw9vtGBiZs9fo7KAZMM8wIqA',
    appId: '1:588664787435:android:688bde5025fdfe3d3ac9ae',
    messagingSenderId: '588664787435',
    projectId: 'mynotes-101-331ef',
    storageBucket: 'mynotes-101-331ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOVQg3q5zfbEDY9BijJV0DzkRPtkj5jEg',
    appId: '1:588664787435:ios:b2c84eac0aa1a5273ac9ae',
    messagingSenderId: '588664787435',
    projectId: 'mynotes-101-331ef',
    storageBucket: 'mynotes-101-331ef.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOVQg3q5zfbEDY9BijJV0DzkRPtkj5jEg',
    appId: '1:588664787435:ios:c0d8413b0394894c3ac9ae',
    messagingSenderId: '588664787435',
    projectId: 'mynotes-101-331ef',
    storageBucket: 'mynotes-101-331ef.appspot.com',
    iosBundleId: 'com.example.expenseTracker.RunnerTests',
  );
}
